- id: maven
  name: maven
  description: Runs arbitrary maven commands for java projects
  entry: maven
  language: python
  pass_filenames: false

- id: maven-test
  name: maven test
  description: Runs maven test build lifecycle
  entry: maven-test
  language: python
  pass_filenames: false

- id: maven-compile
  name: maven compile
  description: Runs maven compile build lifecycle
  entry: maven-compile
  language: python
  pass_filenames: false

- id: maven-checkstyle
  name: maven checkstyle
  description: Runs maven checkstyle build lifecycle
  entry: maven-checkstyle
  language: python
  pass_filenames: false

- id: maven-spotless-check
  name: maven spotless check
  description: Runs spotless:check goal
  entry: maven-spotless-check
  language: python
  pass_filenames: false

- id: maven-spotless-apply
  name: maven spotless apply
  description: Runs spotless:apply goal
  entry: maven-spotless-apply
  language: python
  pass_filenames: false
